"""
Run this ONCE to load your menu into Qdrant.

Usage (from backend/ folder):
    python scripts/ingest_menu.py
"""

import asyncio
import sys
import os
from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.dirname(__file__), '../.env'))
# Add backend to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from services.qdrant_service import ingest_menu

# ─────────────────────────────────────────────
# YOUR MENU DATA — edit this
# ─────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────
# BolKeOrder — Full Menu Dataset (converted from menu.ts)
# 60+ items across 9 categories with vernacular keyword aliases
# and category pairings for upsell suggestions.
# Place this file at: backend/data/menu.py
# ──────────────────────────────────────────────────────────────

MENU = [
    # ── STARTERS ──────────────────────────────────────────────
    {
        "id": "s1",
        "name": "Samosa (2 pcs)",
        "price": 40,
        "category": "starters",
        "isVeg": True,
        "description": "Crispy potato-filled pastry",
        "keywords": ["samosa", "samose", "samosay"],
        "available": True,
    },
    {
        "id": "s2",
        "name": "Paneer Tikka",
        "price": 220,
        "category": "starters",
        "isVeg": True,
        "description": "Grilled cottage cheese with spices",
        "keywords": ["paneer tikka", "paneer tika", "tikka"],
        "available": True,
    },
    {
        "id": "s3",
        "name": "Chicken 65",
        "price": 250,
        "category": "starters",
        "isVeg": False,
        "description": "Deep-fried spicy chicken",
        "keywords": ["chicken 65", "sixty five"],
        "available": True,
    },
    {
        "id": "s4",
        "name": "Veg Spring Roll (4 pcs)",
        "price": 140,
        "category": "starters",
        "isVeg": True,
        "description": "Crispy vegetable rolls",
        "keywords": ["spring roll", "spring rolls"],
        "available": True,
    },
    {
        "id": "s5",
        "name": "Chicken Wings",
        "price": 280,
        "category": "starters",
        "isVeg": False,
        "description": "Spiced crispy chicken wings",
        "keywords": ["wings", "chicken wings"],
        "available": True,
    },
    {
        "id": "s6",
        "name": "Hara Bhara Kebab",
        "price": 180,
        "category": "starters",
        "isVeg": True,
        "description": "Green pea and spinach kebabs",
        "keywords": ["hara bhara kabab", "hara bhara kebab", "kebab", "kabab"],
        "available": True,
    },

    # ── RICE ──────────────────────────────────────────────────
    {
        "id": "r1",
        "name": "Chicken Biryani",
        "price": 350,
        "category": "rice",
        "isVeg": False,
        "description": "Basmati rice with spiced chicken",
        "keywords": ["chicken biryani", "murgh biryani", "biryani"],
        "pairsWellWith": ["b1", "bev3"],
        "available": True,
    },
    {
        "id": "r2",
        "name": "Mutton Biryani",
        "price": 450,
        "category": "rice",
        "isVeg": False,
        "description": "Slow-cooked mutton with rice",
        "keywords": ["mutton biryani", "gosht biryani", "mutton"],
        "pairsWellWith": ["b1", "bev3"],
        "available": True,
    },
    {
        "id": "r3",
        "name": "Veg Biryani",
        "price": 260,
        "category": "rice",
        "isVeg": True,
        "description": "Aromatic vegetable rice",
        "keywords": ["veg biryani", "vegetable biryani"],
        "pairsWellWith": ["b1", "bev3"],
        "available": True,
    },
    {
        "id": "r4",
        "name": "Egg Biryani",
        "price": 280,
        "category": "rice",
        "isVeg": False,
        "description": "Biryani with boiled eggs",
        "keywords": ["egg biryani", "anda biryani", "anda"],
        "pairsWellWith": ["b1"],
        "available": True,
    },
    {
        "id": "r5",
        "name": "Fried Rice",
        "price": 200,
        "category": "rice",
        "isVeg": True,
        "description": "Indo-Chinese egg fried rice",
        "keywords": ["fried rice", "fry rice", "fride rice"],
        "available": True,
    },
    {
        "id": "r6",
        "name": "Curd Rice",
        "price": 120,
        "category": "rice",
        "isVeg": True,
        "description": "Soothing yogurt rice with tempering",
        "keywords": ["curd rice", "dahi rice", "thayir sadam", "thair sadam"],
        "available": True,
    },

    # ── MAIN COURSE VEG ───────────────────────────────────────
    {
        "id": "mv1",
        "name": "Paneer Butter Masala",
        "price": 300,
        "category": "main_veg",
        "isVeg": True,
        "description": "Rich tomato-cream paneer curry",
        "keywords": ["paneer butter masala", "butter paneer", "paneer masala", "paneer"],
        "pairsWellWith": ["b1", "b2"],
        "available": True,
    },
    {
        "id": "mv2",
        "name": "Palak Paneer",
        "price": 280,
        "category": "main_veg",
        "isVeg": True,
        "description": "Spinach and cottage cheese curry",
        "keywords": ["palak paneer", "saag paneer", "palak"],
        "available": True,
    },
    {
        "id": "mv3",
        "name": "Dal Makhani",
        "price": 220,
        "category": "main_veg",
        "isVeg": True,
        "description": "Buttery slow-cooked black lentils",
        "keywords": ["dal makhani", "daal makhani", "makhani dal", "black dal"],
        "pairsWellWith": ["b1", "b3"],
        "available": True,
    },
    {
        "id": "mv4",
        "name": "Dal Tadka",
        "price": 180,
        "category": "main_veg",
        "isVeg": True,
        "description": "Yellow lentils with tempering",
        "keywords": ["dal tadka", "daal tadka", "yellow dal", "daal fry", "dal fry"],
        "available": True,
    },
    {
        "id": "mv5",
        "name": "Mix Veg Curry",
        "price": 240,
        "category": "main_veg",
        "isVeg": True,
        "description": "Seasonal vegetables in onion-tomato gravy",
        "keywords": ["mix veg", "mixed vegetable", "veg curry"],
        "available": True,
    },
    {
        "id": "mv6",
        "name": "Chana Masala",
        "price": 220,
        "category": "main_veg",
        "isVeg": True,
        "description": "Spiced chickpea curry",
        "keywords": ["chana masala", "chole masala", "chole", "chickpea"],
        "available": True,
    },
    {
        "id": "mv7",
        "name": "Aloo Gobi",
        "price": 200,
        "category": "main_veg",
        "isVeg": True,
        "description": "Potato and cauliflower stir-fry",
        "keywords": ["aloo gobi", "aloo gobhi", "potato cauliflower"],
        "available": True,
    },
    {
        "id": "mv8",
        "name": "Kadai Paneer",
        "price": 320,
        "category": "main_veg",
        "isVeg": True,
        "description": "Paneer in spiced bell pepper gravy",
        "keywords": ["kadai paneer", "karahi paneer"],
        "available": True,
    },

    # ── MAIN COURSE NON-VEG ───────────────────────────────────
    {
        "id": "mn1",
        "name": "Butter Chicken",
        "price": 360,
        "category": "main_nonveg",
        "isVeg": False,
        "description": "Mild, creamy tomato chicken curry",
        "keywords": ["butter chicken", "murgh makhani", "butter murgh"],
        "pairsWellWith": ["b1", "b2"],
        "available": True,
    },
    {
        "id": "mn2",
        "name": "Chicken Tikka Masala",
        "price": 380,
        "category": "main_nonveg",
        "isVeg": False,
        "description": "Grilled chicken in smoky masala",
        "keywords": ["chicken tikka masala", "tikka masala"],
        "pairsWellWith": ["b1"],
        "available": True,
    },
    {
        "id": "mn3",
        "name": "Mutton Rogan Josh",
        "price": 420,
        "category": "main_nonveg",
        "isVeg": False,
        "description": "Kashmiri-style braised mutton",
        "keywords": ["rogan josh", "mutton rogan", "rogan"],
        "available": True,
    },
    {
        "id": "mn4",
        "name": "Fish Curry",
        "price": 340,
        "category": "main_nonveg",
        "isVeg": False,
        "description": "Tangy coastal fish in coconut gravy",
        "keywords": ["fish curry", "machli", "meen kuzhambu"],
        "available": True,
    },
    {
        "id": "mn5",
        "name": "Egg Curry",
        "price": 220,
        "category": "main_nonveg",
        "isVeg": False,
        "description": "Boiled eggs in spiced onion gravy",
        "keywords": ["egg curry", "anda curry", "anda masala"],
        "available": True,
    },
    {
        "id": "mn6",
        "name": "Chicken Chettinad",
        "price": 390,
        "category": "main_nonveg",
        "isVeg": False,
        "description": "Spicy South Indian chicken curry",
        "keywords": ["chettinad", "chicken chettinad"],
        "available": True,
    },

    # ── BREADS ────────────────────────────────────────────────
    {
        "id": "b1",
        "name": "Butter Naan",
        "price": 60,
        "category": "breads",
        "isVeg": True,
        "description": "Soft, buttered oven-baked bread",
        "keywords": ["butter naan", "naan", "nan"],
        "available": True,
    },
    {
        "id": "b2",
        "name": "Garlic Naan",
        "price": 80,
        "category": "breads",
        "isVeg": True,
        "description": "Naan topped with garlic and herbs",
        "keywords": ["garlic naan", "garlic nan", "lahsun naan"],
        "available": True,
    },
    {
        "id": "b3",
        "name": "Tandoori Roti",
        "price": 30,
        "category": "breads",
        "isVeg": True,
        "description": "Whole-wheat clay-oven bread",
        "keywords": ["tandoori roti", "roti", "chapati", "chapatti"],
        "available": True,
    },
    {
        "id": "b4",
        "name": "Plain Paratha",
        "price": 50,
        "category": "breads",
        "isVeg": True,
        "description": "Layered unleavened wheat bread",
        "keywords": ["paratha", "parantha", "plain paratha"],
        "available": True,
    },
    {
        "id": "b5",
        "name": "Aloo Paratha",
        "price": 90,
        "category": "breads",
        "isVeg": True,
        "description": "Potato-stuffed fried bread",
        "keywords": ["aloo paratha", "aloo parantha", "potato paratha"],
        "available": True,
    },
    {
        "id": "b6",
        "name": "Poori (4 pcs)",
        "price": 60,
        "category": "breads",
        "isVeg": True,
        "description": "Deep-fried puffed bread",
        "keywords": ["poori", "puri", "puri sabji"],
        "available": True,
    },

    # ── SOUTH INDIAN ──────────────────────────────────────────
    {
        "id": "si1",
        "name": "Masala Dosa",
        "price": 120,
        "category": "south_indian",
        "isVeg": True,
        "description": "Crispy crepe with spiced potato filling",
        "keywords": ["masala dosa", "dosa", "dosha"],
        "pairsWellWith": ["bev2"],
        "available": True,
    },
    {
        "id": "si2",
        "name": "Plain Dosa",
        "price": 80,
        "category": "south_indian",
        "isVeg": True,
        "description": "Thin crispy rice crepe",
        "keywords": ["plain dosa", "sada dosa"],
        "available": True,
    },
    {
        "id": "si3",
        "name": "Rava Dosa",
        "price": 130,
        "category": "south_indian",
        "isVeg": True,
        "description": "Semolina crepe with onion and chillies",
        "keywords": ["rava dosa", "rawa dosa", "semolina dosa"],
        "available": True,
    },
    {
        "id": "si4",
        "name": "Idli Sambar (3 pcs)",
        "price": 80,
        "category": "south_indian",
        "isVeg": True,
        "description": "Steamed rice cakes with lentil soup",
        "keywords": ["idli sambar", "idli", "idly"],
        "pairsWellWith": ["bev2"],
        "available": True,
    },
    {
        "id": "si5",
        "name": "Medu Vada (2 pcs)",
        "price": 90,
        "category": "south_indian",
        "isVeg": True,
        "description": "Crispy lentil doughnuts with sambar",
        "keywords": ["medu vada", "vada", "vade", "vadai"],
        "available": True,
    },
    {
        "id": "si6",
        "name": "Uttapam",
        "price": 110,
        "category": "south_indian",
        "isVeg": True,
        "description": "Thick pancake with onion and tomato",
        "keywords": ["uttapam", "utthapam", "uthappam"],
        "available": True,
    },

    # ── SNACKS ────────────────────────────────────────────────
    {
        "id": "sn1",
        "name": "Pav Bhaji",
        "price": 140,
        "category": "snacks",
        "isVeg": True,
        "description": "Spiced vegetable mash with butter rolls",
        "keywords": ["pav bhaji", "pav", "bhaji"],
        "available": True,
    },
    {
        "id": "sn2",
        "name": "Chole Bhature",
        "price": 160,
        "category": "snacks",
        "isVeg": True,
        "description": "Fluffy fried bread with chickpea curry",
        "keywords": ["chole bhature", "bhature", "chole bature"],
        "available": True,
    },
    {
        "id": "sn3",
        "name": "Vada Pav",
        "price": 50,
        "category": "snacks",
        "isVeg": True,
        "description": "Mumbai's favorite potato slider",
        "keywords": ["vada pav", "vada pao", "wada pav"],
        "available": True,
    },
    {
        "id": "sn4",
        "name": "Aloo Tikki (3 pcs)",
        "price": 80,
        "category": "snacks",
        "isVeg": True,
        "description": "Spiced potato patties",
        "keywords": ["aloo tikki", "aloo tiki", "tikki"],
        "available": True,
    },
    {
        "id": "sn5",
        "name": "Bhel Puri",
        "price": 70,
        "category": "snacks",
        "isVeg": True,
        "description": "Puffed rice with chutneys and sev",
        "keywords": ["bhel puri", "bhel", "puri"],
        "available": True,
    },

    # ── DESSERTS ──────────────────────────────────────────────
    {
        "id": "d1",
        "name": "Gulab Jamun (2 pcs)",
        "price": 80,
        "category": "desserts",
        "isVeg": True,
        "description": "Soft milk-solid balls in rose syrup",
        "keywords": ["gulab jamun", "gulab jamon", "jamun", "sweet"],
        "available": True,
    },
    {
        "id": "d2",
        "name": "Rasmalai (2 pcs)",
        "price": 90,
        "category": "desserts",
        "isVeg": True,
        "description": "Saffron-cream soaked cottage cheese",
        "keywords": ["rasmalai", "ras malai"],
        "available": True,
    },
    {
        "id": "d3",
        "name": "Kheer",
        "price": 100,
        "category": "desserts",
        "isVeg": True,
        "description": "Rice pudding with cardamom and nuts",
        "keywords": ["kheer", "rice pudding", "phirni"],
        "available": True,
    },
    {
        "id": "d4",
        "name": "Gajar Halwa",
        "price": 110,
        "category": "desserts",
        "isVeg": True,
        "description": "Carrot pudding with ghee and milk",
        "keywords": ["gajar halwa", "carrot halwa", "halwa"],
        "available": True,
    },
    {
        "id": "d5",
        "name": "Ice Cream (2 scoops)",
        "price": 120,
        "category": "desserts",
        "isVeg": True,
        "description": "Vanilla/chocolate/mango ice cream",
        "keywords": ["ice cream", "icecream", "ice kream", "kulfi"],
        "available": True,
    },

    # ── BEVERAGES ─────────────────────────────────────────────
    {
        "id": "bev1",
        "name": "Masala Chai",
        "price": 40,
        "category": "beverages",
        "isVeg": True,
        "description": "Spiced Indian milk tea",
        "keywords": ["masala chai", "chai", "tea", "chay"],
        "available": True,
    },
    {
        "id": "bev2",
        "name": "Filter Coffee",
        "price": 60,
        "category": "beverages",
        "isVeg": True,
        "description": "South Indian decoction coffee",
        "keywords": ["filter coffee", "coffee", "kaapi", "kapi"],
        "available": True,
    },
    {
        "id": "bev3",
        "name": "Sweet Lassi",
        "price": 90,
        "category": "beverages",
        "isVeg": True,
        "description": "Chilled sweetened yogurt drink",
        "keywords": ["sweet lassi", "lassi", "dahi lassi"],
        "available": True,
    },
    {
        "id": "bev4",
        "name": "Mango Lassi",
        "price": 110,
        "category": "beverages",
        "isVeg": True,
        "description": "Mango and yogurt smoothie",
        "keywords": ["mango lassi", "aam lassi"],
        "available": True,
    },
    {
        "id": "bev5",
        "name": "Cold Coffee",
        "price": 120,
        "category": "beverages",
        "isVeg": True,
        "description": "Chilled coffee with milk froth",
        "keywords": ["cold coffee", "iced coffee"],
        "available": True,
    },
    {
        "id": "bev6",
        "name": "Fresh Lime Soda",
        "price": 70,
        "category": "beverages",
        "isVeg": True,
        "description": "Tangy sparkling lime drink",
        "keywords": ["lime soda", "nimbu soda", "fresh lime", "nimbu pani"],
        "available": True,
    },
    {
        "id": "bev7",
        "name": "Buttermilk (Chaas)",
        "price": 50,
        "category": "beverages",
        "isVeg": True,
        "description": "Spiced chilled buttermilk",
        "keywords": ["buttermilk", "chaas", "chhas", "mattha"],
        "available": True,
    },
    {
        "id": "bev8",
        "name": "Masala Soda",
        "price": 60,
        "category": "beverages",
        "isVeg": True,
        "description": "Spiced fizzy soda with masala",
        "keywords": ["masala soda"],
        "available": True,
    },
]

async def main():
    print(f"Ingesting {len(MENU)} menu items into Qdrant...")
    await ingest_menu(MENU)
    print("✅ Done! Menu is now searchable via Qdrant.")


if __name__ == "__main__":
    asyncio.run(main())